version: "3.9"

services:
  traefik:
    image: traefik:3.1.6
    container_name: traefik
    command:
      # - --log.level=DEBUG
      # - --accesslog=true
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    networks:
      - shared
    ports:
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 127.0.0.1:8086:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ## QA zone

  flamebin-qa:
    container_name: flamebin-qa
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    networks:
      - shared
    expose:
      - 80
    environment:
      - ENV=qa
      - STORAGE__PATH=/storage
      - DB__PATH=/storage/db/main.db
      - SERVER__PORT=80
    volumes:
      - /flamebin/qa/storage:/storage
    labels:
      traefik.enable: true
      traefik.http.services.flamebin-qa.loadbalancer.server.port: 80
      traefik.http.routers.flamebin-qa.rule: Host(`qa.flamebin.dev`)
      traefik.http.routers.flamebin-qa.entrypoints: web
    restart: unless-stopped

networks:
  shared:
    name: shared
