version: "3.3"

services:

  traefik:
    image: traefik:v2.10.3
    container_name: traefik-qa
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:81"
    ports:
      - 81:81
      # The Web UI (enabled by --api.insecure=true)
      - 127.0.0.1:8086:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  flamebin-qa:
    container_name: flamebin-qa
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      network: host
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - ENV=qa
      - STORAGE__PATH=/storage
      - DB__PATH=/storage/main.db
      - SERVER__PORT=80
    volumes:
      - /flamebin/qa/storage:/storage
    labels:
      traefik.enable: true
      traefik.http.services.flamebin-qa.loadbalancer.server.port: 80
      traefik.http.routers.flamebin-qa.rule: Host(`qa.flamebin.dev`)
      traefik.http.routers.flamebin-qa.entrypoints: web
    restart: unless-stopped
